[package]
name = "fiberhome"
version = "0.1.0"
authors = ["khan"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

new_lib = {path = "../new_lib"}